companies:
  - name: "川恒股份"
    ticker: "002895.SZ"
  - name: "江西铜业"
    ticker: "600362.SS"
  - name: "ASMPT"
    ticker: "0522.HK"
  - name: "腾讯控股"
    ticker: "0700.HK"
  - name: "联想集团"
    ticker: "0992.HK"
  - name: "阿里巴巴"
    ticker: "9988.HK"
  - name: "特变电工"
    ticker: "600089.SS"
  - name: "中国巨石"
    ticker: "600176.SS"
  - name: "中金黄金"
    ticker: "600489.SS"
  - name: "中天科技"
    ticker: "600522.SS"
  - name: "澜起科技"
    ticker: "688008.SS"
  - name: "紫金矿业"
    ticker: "601899.SS"
  - name: "建滔积层板"
    ticker: "1888.HK"
  - name: "光迅科技"
    ticker: "002281.SZ"
  - name: "晶泰科技"
    ticker: "2228.HK"

timeframe: "1y"
