companies:
  # 1. 腾讯控股 - 互联网巨头
  - name: "腾讯控股"
    sector: "INTERNET"
    expected_return: 0.20  # 20% - 基于2024年净利润+41%但营收仅+8%,2025Q1E营收+8-11%,业务成熟增速放缓
    risk:
      mode: "SchemeC"
      beta: 1.05  # 龙头,波动略高于行业
      frag: 2.0   # 脆弱度:监管风险

  # 2. 三花智控 - 汽车零部件(制冷控制)
  - name: "三花智控"
    sector: "CONSUMER"  # 暂用消费代理,汽车零部件
    expected_return: 0.20  # 20% - 基于2024营收+13.8%/利润+6.1%,2025E增长10-15%,PE~35x估值不便宜,下调预期
    risk:
      mode: "SchemeC"
      beta: 1.15  # 汽车零部件周期性
      frag: 2.5   # 脆弱度:下游需求波动

  # 3. 长飞光纤 - 光纤光缆
  - name: "长飞光纤"
    sector: "SEMI"  # 暂用半导体代理,通信设备
    expected_return: 0.12  # 12% - 基于2024营收-8.65%/利润-47.91%,行业需求承压,毛利率虽提升但收入下滑,保守预期
    risk:
      mode: "SchemeC"
      beta: 1.10  # 通信设备周期性
      frag: 2.5   # 脆弱度:价格竞争+需求波动

  # 4. 巨子生物 - 医美生物科技
  - name: "巨子生物"
    sector: "BIOHK"  # 恒生生物科技
    expected_return: 0.25  # 25% - 基于2024营收+57.2%/利润+42.4%,但净利率下滑(42%→37%),销售费用暴涨+72.5%,单品依赖风险,下调预期
    risk:
      mode: "SchemeC"
      beta: 1.25  # 医美高波动
      frag: 3.5   # 脆弱度:竞争加剧+监管+单品风险

  # 5. 雅克科技 - 半导体材料
  - name: "雅克科技"
    sector: "SEMI"
    expected_return: 0.28  # 28% - 基于2024营收+44.84%/利润+50.41%,半导体材料(+71.6%)/光刻胶(+17.7%)强劲,国产替代加速
    risk:
      mode: "SchemeC"
      beta: 1.20  # 半导体周期+成长
      frag: 3.0   # 脆弱度:技术迭代+客户认证

  # 6. 澜起科技 - 半导体内存接口
  - name: "澜起科技"
    sector: "SEMI"
    expected_return: 0.40  # 40% - 基于2024营收+59.2%/利润+213.1%,DDR5份额36.8%全球第一,2025H1E利润+89-106%,强劲增长,上调预期
    risk:
      mode: "SchemeC"
      beta: 1.15  # 半导体周期股,高敏感
      frag: 2.5   # 脆弱度:行业周期+客户集中

  # 7. 中国巨石 - 玻纤龙头
  - name: "中国巨石"
    sector: "NONFER"
    expected_return: 0.22  # 22% - 基于2024营收+6.6%/利润-19.7%,Q4单季利润6.3亿筑底回升,2025E利润30.5亿(+25%),行业复苏中
    risk:
      mode: "SchemeC"
      beta: 1.20  # 周期股,高β
      frag: 3.0   # 脆弱度:周期性强

  # 8. 中金公司 - 券商
  - name: "中金公司"
    sector: "CONSUMER"  # 暂用消费代理,金融服务
    expected_return: 0.24  # 24% - 基于2024营收-7%/利润-8%,但Q4利润+83% YoY,2025E利润75.1亿(+32%),市场环境改善
    risk:
      mode: "SchemeC"
      beta: 1.10  # 券商周期性
      frag: 2.0   # 脆弱度:市场环境依赖

  # 9. 联想集团 - 消费电子
  - name: "联想集团"
    sector: "CONSUMER"  # 消费电子
    expected_return: 0.22  # 22% - 基于24/25财年营收+21.5%/利润+36%,AI PC出货增228%,AI服务器营收+155%,AI驱动增长,上调预期
    risk:
      mode: "SchemeC"
      beta: 1.05  # 消费电子,中性
      frag: 2.5   # 脆弱度:竞争激烈+需求疲软

# ============================================================================
# 期望收益说明 - 基于2024年报及2025年预期的详细研究
# ============================================================================
#
# 【数据来源】基于2024年报实际业绩+2025年分析师预测+行业前景
#
# 高增长(28-40%):
# - 澜起科技40%: 2024营收+59.2%/利润+213.1%,DDR5全球份额36.8%第一,2025H1E利润+89-106%
#   → 数据支撑:DDR5放量超预期,新产品PCIe/MRCD/MDB营收4.22亿(8倍),强劲增长持续
#
# - 雅克科技28%: 2024营收+44.84%/利润+50.41%,半导体材料+71.6%/光刻胶+17.7%
#   → 数据支撑:国产替代加速,收购韩国SKC湿化学品业务,LDS设备国内市占率领先
#
# 稳健增长(22-25%):
# - 巨子生物25%: 2024营收+57.2%/利润+42.4%,但净利率下滑42%→37%,销售费用+72.5%
#   → 调整理由:虽增速高但盈利质量下降,单品(可复美82%收入)依赖风险,竞争加剧,从35%下调至25%
#
# - 中金公司24%: 2024营收-7%/利润-8%,但Q4利润+83% YoY,2025E利润+32%至75.1亿
#   → 数据支撑:Q4强劲反弹,2025市场环境改善,投行M&A第一+财富管理增长
#
# - 中国巨石22%: 2024营收+6.6%/利润-19.7%,Q4单季利润6.3亿筑底,2025E利润30.5亿(+25%)
#   → 数据支撑:玻纤价格持续修复,电子布复价,销量+21.9%,行业竞争改善,盈利底部回升
#
# - 联想集团22%: 24/25财年营收+21.5%/利润+36%,AI PC出货环比+228%,AI服务器营收+155%
#   → 调整理由:AI驱动超预期,全球市场双位数增长,从18%上调至22%
#
# 温和/低增长(12-20%):
# - 腾讯控股20%: 2024营收+8%/利润+41%,2025Q1E营收+8-11%
#   → 调整理由:利润增长主要靠成本控制,营收增速放缓,业务成熟,从25%下调至20%
#
# - 三花智控20%: 2024营收+13.8%/利润+6.1%,2025Q1营收+19.1%/利润+39.47%,2025-27E增长10-25%
#   → 调整理由:虽有新能源汽车+热管理增长点,但PE~35x估值不便宜,从28%下调至20%
#
# - 长飞光纤12%: 2024营收-8.65%/利润-47.91%,毛利率24.5%→27.9%
#   → 调整理由:光纤需求承压,虽毛利率提升但收入下滑,行业竞争激烈,从20%下调至12%
#
# ============================================================================
# 调整总结
# ============================================================================
#
# 上调(2家):
# - 澜起科技: 35%→40% (+5%) - DDR5超预期,2025H1E利润+89-106%
# - 联想集团: 18%→22% (+4%) - AI PC/AI服务器驱动,业绩超预期
#
# 下调(5家):
# - 腾讯控股: 25%→20% (-5%) - 营收增速放缓,业务成熟
# - 三花智控: 28%→20% (-8%) - 估值不便宜,调整预期至合理水平
# - 长飞光纤: 20%→12% (-8%) - 营收利润双降,行业承压
# - 巨子生物: 35%→25% (-10%) - 盈利质量下降,单品风险,竞争加剧
# - 雅克科技: 32%→28% (-4%) - 微调至更稳健水平
#
# 上调(1家):
# - 中金公司: 22%→24% (+2%) - Q4强反弹,2025E利润+32%
#
# 维持(1家):
# - 中国巨石: 24%→22% (-2%) - 微调,盈利筑底回升
#
# ============================================================================
