companies:
  # 1. 联想集团 - 消费电子 (港股 00992.HK)
  - name: "联想集团"
    sector: "CONSUMER"
    expected_return: 0.22  # 22% = 20%(催化) + 2%(估值调整:PE 8.83x低于行业平均)
    risk:
      mode: "SchemeC"
      beta: 1.05
      frag: 2.5
    valuation_notes: "PE 8.83x (GuruFocus), 中信证券目标价11港元,估值低估"

  # 2. 澜起科技 - 半导体内存接口 (A股 688008.SH)
  - name: "澜起科技"
    sector: "SEMI"
    expected_return: 0.45  # 45% = 43%(催化) + 2%(估值调整:PE历史分位15.38%,处于低估值区间)
    risk:
      mode: "SchemeC"
      beta: 1.15
      frag: 2.5
    valuation_notes: "PE 56.51x, 历史分位15.38% (知了财报网 2025-07-25), 处于5年历史低估值区间"

  # 3. 中金黄金 - 黄金矿企 (A股 600489.SH)
  - name: "中金黄金"
    sector: "GOLD"
    expected_return: 0.22  # 22% = 18%(催化) + 4%(估值调整:PE 18.6x, PS 1.47x远低于同业)
    risk:
      mode: "SchemeC"
      beta: 0.95
      frag: 2.0
    valuation_notes: "PE 18.6x, PS 1.47x远低于赤峰黄金5.57x/紫金矿业2.44x (理杏仁 2025-04-29)"

  # 4. ASMPT - 半导体封装设备 (港股 00522.HK)
  - name: "ASMPT"
    sector: "SEMI"
    expected_return: 0.25  # 25% = 25%(催化) + 0%(估值调整:缺乏准确PE数据,暂不调整)
    risk:
      mode: "SchemeC"
      beta: 1.20
      frag: 3.0
    valuation_notes: "麦格理目标价75港元, 摩根士丹利目标价130港元 (2024-07), 缺乏实时PE数据,保守估计"

  # 5. 中天科技 - 光纤光缆+海缆 (A股 600522.SH)
  - name: "中天科技"
    sector: "SEMI"
    expected_return: 0.10  # 10% = 10%(催化) + 0%(估值调整:PE历史分位42.23%,合理)
    risk:
      mode: "SchemeC"
      beta: 1.10
      frag: 2.5
    valuation_notes: "PE 16.97x (扣非), 历史分位42.23% (理杏仁), 估值合理"

  # 6. 中国巨石 - 玻纤龙头 (A股 600176.SH)
  - name: "中国巨石"
    sector: "NONFER"
    expected_return: 0.19  # 19% = 22%(催化) - 3%(估值调整:PB 1.5x略高于行业均值1.3x)
    risk:
      mode: "SchemeC"
      beta: 1.20
      frag: 3.0
    valuation_notes: "PB 1.5x vs 行业均值1.3x (小牛行研 2025-03), 估值合理偏高"

  # 7. 建滔积层板 - CCL覆铜板龙头 (港股 01888.HK)
  - name: "建滔积层板"
    sector: "NONFER"
    expected_return: 0.24  # 24% = 30%(催化) - 6%(估值调整:静态PE 30.75x偏高,但2025E PE降至10.7x)
    risk:
      mode: "SchemeC"
      beta: 1.05
      frag: 2.0
    valuation_notes: "静态PE 30.75x, 2025E PE 10.7x (国金证券), 当前估值偏高但业绩快速增长"

  # 8. 江西铜业 - 铜矿龙头 (A股 600362.SH)
  - name: "江西铜业"
    sector: "NONFER"
    expected_return: 0.15  # 15% = 12%(催化) + 3%(估值调整:PB接近2008金融危机低位)
    risk:
      mode: "SchemeC"
      beta: 1.15
      frag: 2.5
    valuation_notes: "PB接近历史低位 (市场分析), 估值低估"

  # 9. 紫金矿业 - 黄金+铜综合矿企 (港股 02899.HK + A股 601899.SH)
  - name: "紫金矿业"
    sector_mix:
      NONFER: 0.6  # 60%铜
      GOLD: 0.4    # 40%黄金
    expected_return: 0.28  # 28% = 28%(催化) + 0%(估值调整:PE 14.51x接近3年均值15.85x,估值合理)
    risk:
      mode: "SchemeC"
      beta: 0.95
      frag: 1.5
    valuation_notes: "PE 14.51x接近3年均值15.85x, 较历史最低9x溢价60% (证券时报 2025-04), 估值合理非低估"

  # 10. 雅克科技 - 半导体材料 (A股 002409.SZ)
  - name: "雅克科技"
    sector: "SEMI"
    expected_return: 0.28  # 28% = 28%(催化) + 0%(估值调整:PE 28x与+50%增速匹配,PEG 0.56合理)
    risk:
      mode: "SchemeC"
      beta: 1.20
      frag: 3.0
    valuation_notes: "PE 28.12x, PEG 0.56 (新浪财经 2025-05), 估值合理"

  # 11. 生益科技 - CCL覆铜板 (A股 600183.SH)
  - name: "生益科技"
    sector: "NONFER"
    expected_return: 0.35  # 35% = 35%(催化) + 0%(估值调整:PE 18.9-23.4x接近合理,无明显高估低估)
    risk:
      mode: "SchemeC"
      beta: 1.10
      frag: 2.5
    valuation_notes: "2025E PE 18.9-23.4x (招商证券/同花顺), 估值合理"

  # 12. 光迅科技 - 光模块+光器件 (A股 002281.SZ)
  - name: "光迅科技"
    sector: "SEMI"
    expected_return: 0.32  # 32% = 42%(催化) - 10%(估值调整:PE历史分位90.73%,严重高估)
    risk:
      mode: "SchemeC"
      beta: 1.15
      frag: 2.5
    valuation_notes: "PE 64.55x, 历史分位90.73% (英为财情), 严重高估"

  # 13. 特变电工 - 变压器+新能源 (A股 600089.SH)
  - name: "特变电工"
    sector: "NONFER"
    expected_return: 0.22  # 22% = 18%(催化) + 4%(估值调整:PE 13.33x远低于光伏板块44.45x/22.74x)
    risk:
      mode: "SchemeC"
      beta: 1.10
      frag: 2.0
    valuation_notes: "PE 13.33x, PB 1.28x, 远低于光伏板块同业 (东方财富网 2025-06-05), 严重低估"

  # 14. 川恒股份 - 磷化工+新能源材料 (A股 002895.SZ)
  - name: "川恒股份"
    sector: "NONFER"
    expected_return: 0.28  # 28% = 26%(催化) + 2%(估值调整:PE 9.88x低估)
    risk:
      mode: "SchemeC"
      beta: 1.15
      frag: 2.5
    valuation_notes: "2025E PE 9.88x (市场预测), 估值低估"

# ============================================================================
# 估值调整说明 (V4修正版) - 基于准确数据源
# ============================================================================
#
# 【核心修正】
# 紫金矿业估值修正:
# - V3版本错误: PE 13.09x严重低估 (数据源不明确)
# - V4修正: PE 14.51x接近3年均值15.85x,较历史最低9x溢价60% (证券时报 2025-04)
# - 估值判断: 合理 (非严重低估)
# - 调整幅度: 0% (从+5%修正为0%)
# - 期望收益: 28% (从33%修正为28%)
#
# 【调整后排名预期】
# 紫金矿业VTR预期从2.01下降至约1.70,排名预期从第1下降至第5-6位
#
# ============================================================================
# 估值调整逻辑框架 (V4修正版)
# ============================================================================
#
# 大幅上调(+4%至+5%):
# - 特变电工: 18%→22% (+4%) - PE 13.33x远低于光伏板块,严重低估
# - 中金黄金: 18%→22% (+4%) - PE 18.6x, PS 1.47x远低于同业
#
# 适度上调(+2%至+3%):
# - 澜起科技: 43%→45% (+2%) - PE历史分位15.38%,处于低估值区间
# - 联想集团: 20%→22% (+2%) - PE 8.83x低于行业平均
# - 江西铜业: 12%→15% (+3%) - PB接近2008金融危机低位
# - 川恒股份: 26%→28% (+2%) - PE 9.88x低估
#
# 维持(0%):
# - 雅克科技28%: PE 28x与+50%增速匹配,PEG 0.56合理
# - 中天科技10%: PE历史分位42.23%,合理
# - ASMPT 25%: 缺乏准确PE数据,保守维持
# - 紫金矿业28%: PE 14.51x接近3年均值,估值合理 (修正)
# - 生益科技35%: 2025E PE 18.9-23.4x合理 (修正)
#
# 适度下调(-3%至-6%):
# - 中国巨石: 22%→19% (-3%) - PB 1.5x略高于行业均值1.3x
# - 建滔积层板: 30%→24% (-6%) - 静态PE 30.75x偏高,但2025E PE降至10.7x (修正)
#
# 大幅下调(-10%):
# - 光迅科技: 42%→32% (-10%) - PE历史分位90.73%,严重高估
#
# ============================================================================
# 数据来源汇总 (V4版本)
# ============================================================================
#
# 港股数据:
# - 紫金矿业 02899.HK: 证券时报网 2025-04-01, 理杏仁
# - 联想集团 00992.HK: GuruFocus, 理杏仁, 中信证券研报
# - ASMPT 00522.HK: 麦格理研报 2025-07, 摩根士丹利研报 2024-07
# - 建滔积层板 01888.HK: 国金证券研报, 富途牛牛
#
# A股数据:
# - 澜起科技 688008.SH: 知了财报网 2025-07-25
# - 光迅科技 002281.SZ: 英为财情
# - 生益科技 600183.SH: 招商证券研报, 同花顺
# - 雅克科技 002409.SZ: 新浪财经 2025-05, 理杏仁
# - 中国巨石 600176.SH: 小牛行研 2025-03
# - 特变电工 600089.SH: 东方财富网 2025-06-05
# - 中天科技 600522.SH: 理杏仁
# - 中金黄金 600489.SH: 理杏仁 2025-04-29
#
# ============================================================================
# 数据质量评级
# ============================================================================
#
# A级(高质量-历史分位数据):
# - 澜起科技: PE历史分位15.38% ⭐️
# - 光迅科技: PE历史分位90.73% ⭐️
# - 中天科技: PE历史分位42.23% ⭐️
#
# B级(中高质量-多源验证):
# - 紫金矿业: PE 14.51x (证券时报+理杏仁) ⭐️
# - 联想集团: PE 8.83-12.5x (GuruFocus+理杏仁) ⭐️
# - 特变电工: PE 13.33x (东方财富网) ⭐️
# - 生益科技: 2025E PE 18.9-23.4x (券商研报) ⭐️
#
# C级(中等质量-单一来源):
# - 中金黄金: PE 18.6x (理杏仁)
# - 雅克科技: PE 28.12x (新浪财经)
# - 中国巨石: PB 1.5x (小牛行研)
# - 建滔积层板: PE 30.75x/10.7x (国金证券)
#
# D级(低质量-数据缺失):
# - ASMPT: 缺乏实时PE数据,仅有分析师目标价
# - 江西铜业: 仅有定性描述,缺乏具体数值
# - 川恒股份: 2025E PE 9.88x (来源不明)
#
# ============================================================================
# 后续改进计划
# ============================================================================
#
# 1. 补充缺失数据:
#    - ASMPT: 通过港交所或Bloomberg获取实时PE
#    - 江西铜业: 查询东方财富网/理杏仁获取具体PB数值
#    - 川恒股份: 验证PE数据来源
#
# 2. 建立自动化数据采集:
#    - 开发Python脚本定期抓取理杏仁/东方财富网数据
#    - 存储历史估值数据,计算历史分位
#
# 3. 估值预警机制:
#    - PE历史分位变化>10%触发警报
#    - 股价涨跌幅>15%触发重估
#
# ============================================================================
