companies:
  # 1. 联想集团 - 消费电子
  - name: "联想集团"
    sector: "CONSUMER"
    expected_return: 0.20  # 20% - (下调-2%) AI PC贡献有限,PC整体增速温和(IDC 2025E +4%)
    risk:
      mode: "SchemeC"
      beta: 1.05
      frag: 2.5

  # 2. 澜起科技 - 半导体内存接口
  - name: "澜起科技"
    sector: "SEMI"
    expected_return: 0.43  # 43% - (上调+3%) DDR5渗透率加速+2025Q1净利+128-146%+新品PCIe/MRCD/MDB Q1营收+155%+寡头垄断(36.8%份额第一,IDT退出,Rambus落后)
    risk:
      mode: "SchemeC"
      beta: 1.15
      frag: 2.5

  # 3. 中金黄金 - 黄金矿企
  - name: "中金黄金"
    sector: "GOLD"
    expected_return: 0.18  # 18% - (上调+3%) 金价2025E 3000-3200美元(+20-30%)+纱岭金矿(200吨储量)2025投产+央行购金+避险+降息三重驱动
    risk:
      mode: "SchemeC"
      beta: 0.95
      frag: 2.0

  # 4. ASMPT - 半导体封装设备
  - name: "ASMPT"
    sector: "SEMI"
    expected_return: 0.25  # 25% - (下调-3%) 虽先进封装+23%占比升至30%,TCB获HBM订单,但整体营收-10%,SMT承压(占49%),混合键合弱于BESI
    risk:
      mode: "SchemeC"
      beta: 1.20
      frag: 3.0

  # 5. 中天科技 - 光纤光缆+海缆
  - name: "中天科技"
    sector: "SEMI"
    expected_return: 0.10  # 10% - (下调-2%) 光通信业务-10亿行业低谷难扭转,海缆持平无增长,在手订单134亿但转化慢
    risk:
      mode: "SchemeC"
      beta: 1.10
      frag: 2.5

  # 6. 中国巨石 - 玻纤龙头
  - name: "中国巨石"
    sector: "NONFER"
    expected_return: 0.22  # 22% - (维持) Q4筑底6.3亿,2025E利润+25%至30.5亿,玻纤价格修复+电子布复价+销量+21.9%
    risk:
      mode: "SchemeC"
      beta: 1.20
      frag: 3.0

  # 7. 建滔积层板 - CCL覆铜板龙头
  - name: "建滔积层板"
    sector: "NONFER"
    expected_return: 0.30  # 30% - (维持) 全球市占率15%第一+一体化成本优势+2024年3月/5月两次涨价+产能打满+AI服务器PCB订单排至2026
    risk:
      mode: "SchemeC"
      beta: 1.05
      frag: 2.0

  # 8. 江西铜业 - 铜矿龙头
  - name: "江西铜业"
    sector: "NONFER"
    expected_return: 0.12  # 12% - (下调-3%) 2024营收-0.18%产量乏力,扣非+54%靠非经常性损益,无产能投产催化,相比紫金矿业催化明显不足
    risk:
      mode: "SchemeC"
      beta: 1.15
      frag: 2.5

  # 9. 紫金矿业 - 黄金+铜综合矿企
  - name: "紫金矿业"
    sector_mix:
      NONFER: 0.6  # 60%铜
      GOLD: 0.4    # 40%黄金
    expected_return: 0.28  # 28% - (上调+3%) 铜金量价齐升(铜+6%/金+8%/净利+52%)+Kamoa三期投产年产60万吨++资源储量丰富(铜1.1亿吨/金4000吨)+成本行业低位
    risk:
      mode: "SchemeC"
      beta: 0.95
      frag: 1.5

  # 10. 雅克科技 - 半导体材料
  - name: "雅克科技"
    sector: "SEMI"
    expected_return: 0.28  # 28% - (维持) 2024营收+44.84%/利润+50.41%,半导体材料+71.6%,国产替代加速,收购韩国SKC湿化学品
    risk:
      mode: "SchemeC"
      beta: 1.20
      frag: 3.0

  # 11. 生益科技 - CCL覆铜板
  - name: "生益科技"
    sector: "NONFER"
    expected_return: 0.35  # 35% - (上调+3%) 2025H1净利+53%超预期+高端产品占比15%→22%出货量+50%+英伟达/亚马逊认证应用GB200+AI服务器CCL需求CAGR 26% vs 产能7%(供需缺口3年)+涨价(高多层板+12%)
    risk:
      mode: "SchemeC"
      beta: 1.10
      frag: 2.5

  # 12. 光迅科技 - 光模块+光器件
  - name: "光迅科技"
    sector: "SEMI"
    expected_return: 0.42  # 42% - (上调+4%) 2025Q1营收+72%/利润+95%爆发式增长+800G批量出货+1.6T 2025商用元年+产能爬坡(高端产业基地)+Q2毛利率提升(800G占比↑/硅光占比↑/良率↑)+阿里云2025导入800G
    risk:
      mode: "SchemeC"
      beta: 1.15
      frag: 2.5

  # 13. 特变电工 - 变压器+新能源
  - name: "特变电工"
    sector: "NONFER"
    expected_return: 0.18  # 18% - (维持) 变压器+21%毛利率提升受益电网投资+AI数据中心,但多晶硅-34%拖累(营收185亿毛利率仅1.41%)
    risk:
      mode: "SchemeC"
      beta: 1.10
      frag: 2.0

  # 14. 川恒股份 - 磷化工+新能源材料
  - name: "川恒股份"
    sector: "NONFER"
    expected_return: 0.26  # 26% - (下调-2%) 磷化工+46.66%强劲+磷矿储量1.76亿吨品位>25%+磷酸铁锂产能规划100万吨(2026)+战略客户国轩/富临/欣旺达,但转型收益期拉长,磷酸铁锂价格2024大跌
    risk:
      mode: "SchemeC"
      beta: 1.15
      frag: 2.5

# ============================================================================
# 期望收益说明 - 基于深度行业分析及个股催化因素
# ============================================================================
#
# 【分析维度】行业景气度 + 供需格局 + 个股催化因素 + 竞争壁垒
#
# 【调整说明】
#
# 上调(+3%至+4%):
# - 澜起科技: 40%→43% (+3%) - DDR5寡头垄断+2025Q1净利+128-146%+新品爆发
# - 光迅科技: 38%→42% (+4%) - 2025Q1营收+72%/利润+95%+800G/1.6T迭代
# - 生益科技: 32%→35% (+3%) - AI服务器CCL供需缺口3年+客户认证突破+涨价
# - 紫金矿业: 25%→28% (+3%) - 铜金量价齐升+资源储量+成本优势
# - 中金黄金: 15%→18% (+3%) - 金价预期大涨+纱岭投产
#
# 下调(-2%至-3%):
# - ASMPT: 28%→25% (-3%) - 先进封装强劲但SMT拖累,整体营收-10%
# - 江西铜业: 15%→12% (-3%) - 营收持平,催化不足
# - 联想集团: 22%→20% (-2%) - AI PC贡献有限,PC整体增速温和
# - 川恒股份: 28%→26% (-2%) - 新能源转型收益期拉长
# - 中天科技: 12%→10% (-2%) - 光通信低谷难扭转
#
# 维持:
# - 建滔积层板30%: 全球第一+一体化+涨价
# - 雅克科技28%: 半导体材料稳健
# - 中国巨石22%: 周期底部复苏
# - 特变电工18%: 变压器强劲,多晶硅拖累
#
# ============================================================================
# 行业深度分析要点
# ============================================================================
#
# 【半导体/光通信】复苏向上,AI驱动
#
# 1. DDR5内存接口(澜起科技):
#    - 行业:DDR5渗透率2025年持续加速,AI服务器拉动,存储芯片涨价30%
#    - 供给:寡头垄断(澜起36.8%第一,IDT退出,Rambus落后)
#    - 催化:2025年服务器DDR5渗透率>70%,新品PCIe/MRCD/MDB Q1营收+155%
#
# 2. 先进封装(ASMPT):
#    - 行业:CoWoS产能翻倍,HBM渗透率9%→18%→30%+,HBM3→HBM3e
#    - 供给:TCB设备ASMPT vs K&S双寡头,全球安装500+台
#    - 催化:获SK海力士+两家HBM客户订单,12层HBM应用,2025继续放量
#    - 风险:SMT承压(占49%),整体营收-10%,混合键合弱于BESI
#
# 3. 光模块(光迅科技):
#    - 行业:技术迭代加速至2年,800G大规模出货,1.6T 2025商用,AI数通CAGR 47%
#    - 供给:全球Top10中国占7家,光迅全球光器件5.8%(第四)
#    - 催化:2025Q1营收+72%/利润+95%,800G批量出货,产能爬坡,阿里云2025导入800G
#
# 【CCL/PCB】AI驱动超级周期
#
# 1. 行业景气:
#    - PCB订单排至2026年,价格上涨(高多层板+12%,HDI+8%),产能紧张(利用率>90%)
#    - AI服务器PCB从8层→20-30层,高端材料升级
#    - 供需缺口:未来3年高阶HDI产能比需求短缺30%,AI服务器CCL需求CAGR 26% vs 产能7%
#
# 2. 生益科技:
#    - 催化:2025H1净利+53%,高端产品占比15%→22%,出货量+50%
#    - 客户:英伟达/亚马逊认证,应用GB200,M7/M8供货谷歌/AWS
#    - 产能:追加投资2.91亿,新增1800万m²CCL,AI服务器占35%
#
# 3. 建滔积层板:
#    - 市场地位:全球15%市占率第一,一体化成本优势
#    - 催化:2024年两次涨价,产能打满,2024H1净利+72.36%
#
# 【有色金属/资源】量价齐升
#
# 1. 铜(紫金矿业):
#    - 价格:高盛预测2025年LME铜价均价9890美元,峰值10050美元
#    - 催化:矿产铜+6%至107万吨(全球前四,占中国65%),Kamoa三期投产达产60万吨+
#    - 成本:铜精矿成本环比-4.3%,全球行业低位
#    - 资源:铜储量1.1亿吨,金4000吨,锂1800万吨碳酸锂当量
#    - 风险:Kamoa矿震2025减产15-20万吨,但不改长期趋势
#
# 2. 铜(江西铜业):
#    - 问题:2024营收-0.18%,产量乏力,无产能投产催化
#    - 扣非+54%主要靠非经常性损益,持续性存疑
#
# 3. 黄金(中金黄金):
#    - 价格:瑞银预测2025年高点3200美元(+20-30%),机构普遍看涨3000美元+
#    - 驱动:央行购金+避险(地缘政治)+降息(美联储2025年预计2次)
#    - 催化:纱岭金矿(储量200吨)2025年投产,显著增厚产能
#
# 4. 磷化工(川恒股份):
#    - 资源:磷矿储量1.76亿吨,品位>25%(全国均值16.85%)
#    - 新能源:磷酸铁60万吨规划(10万吨在建+与国轩50万吨),2026目标100万吨
#    - 客户:国轩控股、富临精工、欣旺达战略合作
#    - 风险:磷酸铁锂价格2024大跌,转型收益期拉长
#
# 5. 玻纤(中国巨石):
#    - 周期底部:2024利润-19.7%,Q4筑底6.3亿,2025E利润+25%
#    - 催化:玻纤价格修复,电子布复价,销量+21.9%
#    - 风险:周期性强,复苏持续性存疑
#
# 6. 变压器(特变电工):
#    - 强劲:变压器营收223.64亿(+21%),毛利率+1.62pcts,产量4.20亿kVA行业前三
#    - 拖累:多晶硅营收185亿(-34%),毛利率仅1.41%,供需失衡价格暴跌
#
# 【消费电子】
#
# 1. 联想集团:
#    - 业绩:24/25财年营收+21.5%/利润+36%,AI PC出货环比+228%,AI服务器营收+155%
#    - 问题:IDC预计2025年PC出货量+4%(vs 2024年+3%),增速温和
#    - AI PC占比提升需时间,短期贡献有限
#
# ============================================================================
