companies:
  # 1. 联想集团 - 消费电子
  - name: "联想集团"
    sector: "CONSUMER"
    expected_return: 0.22  # 22% = 20%(催化) + 2%(估值调整:PE低于行业平均)
    risk:
      mode: "SchemeC"
      beta: 1.05
      frag: 2.5

  # 2. 澜起科技 - 半导体内存接口
  - name: "澜起科技"
    sector: "SEMI"
    expected_return: 0.45  # 45% = 43%(催化) + 2%(估值调整:PE 55.38x低于行业中位68.5x)
    risk:
      mode: "SchemeC"
      beta: 1.15
      frag: 2.5

  # 3. 中金黄金 - 黄金矿企
  - name: "中金黄金"
    sector: "GOLD"
    expected_return: 0.22  # 22% = 18%(催化) + 4%(估值调整:PE 14.67x低于同业)
    risk:
      mode: "SchemeC"
      beta: 0.95
      frag: 2.0

  # 4. ASMPT - 半导体封装设备
  - name: "ASMPT"
    sector: "SEMI"
    expected_return: 0.13  # 13% = 25%(催化) - 12%(估值调整:PE 120x极度高估,整体营收-10%)
    risk:
      mode: "SchemeC"
      beta: 1.20
      frag: 3.0

  # 5. 中天科技 - 光纤光缆+海缆
  - name: "中天科技"
    sector: "SEMI"
    expected_return: 0.10  # 10% = 10%(催化) + 0%(估值调整:PE历史42.23%分位,合理)
    risk:
      mode: "SchemeC"
      beta: 1.10
      frag: 2.5

  # 6. 中国巨石 - 玻纤龙头
  - name: "中国巨石"
    sector: "NONFER"
    expected_return: 0.19  # 19% = 22%(催化) - 3%(估值调整:PB 1.5x略高于行业均值1.3x)
    risk:
      mode: "SchemeC"
      beta: 1.20
      frag: 3.0

  # 7. 建滔积层板 - CCL覆铜板龙头
  - name: "建滔积层板"
    sector: "NONFER"
    expected_return: 0.22  # 22% = 30%(催化) - 8%(估值调整:近期暴涨>200%,已反映短期增长)
    risk:
      mode: "SchemeC"
      beta: 1.05
      frag: 2.0

  # 8. 江西铜业 - 铜矿龙头
  - name: "江西铜业"
    sector: "NONFER"
    expected_return: 0.15  # 15% = 12%(催化) + 3%(估值调整:PB接近2008金融危机低位)
    risk:
      mode: "SchemeC"
      beta: 1.15
      frag: 2.5

  # 9. 紫金矿业 - 黄金+铜综合矿企
  - name: "紫金矿业"
    sector_mix:
      NONFER: 0.6  # 60%铜
      GOLD: 0.4    # 40%黄金
    expected_return: 0.33  # 33% = 28%(催化) + 5%(估值调整:PE 13.09x严重低于同业24.58x-40x)
    risk:
      mode: "SchemeC"
      beta: 0.95
      frag: 1.5

  # 10. 雅克科技 - 半导体材料
  - name: "雅克科技"
    sector: "SEMI"
    expected_return: 0.28  # 28% = 28%(催化) + 0%(估值调整:PE 28x与+50%增速匹配,PEG 0.56合理)
    risk:
      mode: "SchemeC"
      beta: 1.20
      frag: 3.0

  # 11. 生益科技 - CCL覆铜板
  - name: "生益科技"
    sector: "NONFER"
    expected_return: 0.38  # 38% = 35%(催化) + 3%(估值调整:PE 19.34x低于行业均值25x)
    risk:
      mode: "SchemeC"
      beta: 1.10
      frag: 2.5

  # 12. 光迅科技 - 光模块+光器件
  - name: "光迅科技"
    sector: "SEMI"
    expected_return: 0.32  # 32% = 42%(催化) - 10%(估值调整:PE历史90.73%分位,严重高估)
    risk:
      mode: "SchemeC"
      beta: 1.15
      frag: 2.5

  # 13. 特变电工 - 变压器+新能源
  - name: "特变电工"
    sector: "NONFER"
    expected_return: 0.22  # 22% = 18%(催化) + 4%(估值调整:PE 13.33x远低于光伏板块44.45x/22.74x)
    risk:
      mode: "SchemeC"
      beta: 1.10
      frag: 2.0

  # 14. 川恒股份 - 磷化工+新能源材料
  - name: "川恒股份"
    sector: "NONFER"
    expected_return: 0.28  # 28% = 26%(催化) + 2%(估值调整:PE 9.88x低估,资源价值未充分反映)
    risk:
      mode: "SchemeC"
      beta: 1.15
      frag: 2.5

# ============================================================================
# 估值调整说明 - 基于当前估值水平的期望收益调整
# ============================================================================
#
# 【核心公式】
# 期望收益率 = 基于催化因素的内在增长率 + 估值调整系数
#
# 【估值调整逻辑】
#
# 大幅上调(+4%至+5%):
# - 紫金矿业: 28%→33% (+5%) - PE 13.09x严重低于同业(24.58x-40x),资源丰富成本低
# - 特变电工: 18%→22% (+4%) - PE 13.33x远低于光伏板块,变压器业务强劲
# - 中金黄金: 18%→22% (+4%) - PE 14.67x低于同业,纱岭金矿投产催化
#
# 适度上调(+2%至+3%):
# - 生益科技: 35%→38% (+3%) - PE 19.34x低于行业均值25x,AI服务器CCL供需缺口
# - 澜起科技: 43%→45% (+2%) - PE 55.38x低于行业中位68.5x,DDR5寡头垄断
# - 联想集团: 20%→22% (+2%) - PE低于行业平均,AI PC/AI服务器增长潜力
# - 江西铜业: 12%→15% (+3%) - PB接近2008金融危机低位
# - 川恒股份: 26%→28% (+2%) - PE 9.88x低估,磷矿资源价值未充分反映
#
# 维持(0%):
# - 雅克科技28%: PE 28x与+50%增速匹配,PEG 0.56合理
# - 中天科技10%: PE历史42.23%分位,中等水平,估值合理
#
# 适度下调(-3%):
# - 中国巨石: 22%→19% (-3%) - PB 1.5x略高于行业均值1.3x,周期性复苏不确定
#
# 大幅下调(-8%至-12%):
# - 建滔积层板: 30%→22% (-8%) - 近期暴涨>200%,估值已充分反映短期增长
# - 光迅科技: 42%→32% (-10%) - PE历史90.73%分位,严重高估,估值回归风险
# - ASMPT: 25%→13% (-12%) - PE 120x极度高估,整体营收-10%,估值与业绩不匹配
#
# ============================================================================
# 估值数据来源
# ============================================================================
#
# 数据来源:
# - PE/PB数据: 理杏仁、东方财富网、英为财情、价值大师
# - 历史分位: 理杏仁、知了财报网
# - 行业对比: 券商研报、行业数据库
# - 采集时间: 2025年6月-10月
#
# 估值调整方法论:
# 1. PE历史分位 >80%: 高估,调整 -8%至-12%
# 2. PE历史分位 40%-60%: 合理,调整 0%
# 3. PE历史分位 <20%: 低估,调整 +3%至+5%
# 4. PB接近历史低位: 额外 +2%至+3%
# 5. PE显著低于同业(>30%): 额外 +3%至+5%
# 6. 近期暴涨>150%: 调整 -5%至-10%
#
# ============================================================================
# 关键投资洞察
# ============================================================================
#
# 【高VTR且估值合理/低估组合】(推荐)
# 1. 澜起科技 (45%,估值合理偏低,DDR5寡头)
# 2. 生益科技 (38%,估值低于行业,AI服务器CCL供需缺口)
# 3. 紫金矿业 (33%,估值严重低估,铜金量价齐升)
# 4. 雅克科技 (28%,估值合理,半导体材料国产替代)
# 5. 川恒股份 (28%,估值低估,磷矿资源稀缺)
#
# 【需警惕高估值风险】
# 1. 光迅科技 (PE历史90.73%分位,虽业绩强劲但估值透支)
# 2. ASMPT (PE 120x,整体营收-10%,估值与业绩不匹配)
# 3. 建滔积层板 (近期暴涨>200%,获利回吐风险)
#
# 【估值修复潜力股】(左侧布局)
# 1. 特变电工 (PE 13.33x,变压器强劲,估值远低于光伏板块)
# 2. 中金黄金 (PE 14.67x,纱岭金矿投产,金价上行)
# 3. 江西铜业 (PB接近历史低位,铜价上行趋势)
#
# ============================================================================
