companies:
  # 1. 联想集团 - 消费电子（已分析）
  - name: "联想集团"
    sector: "CONSUMER"
    expected_return: 0.22  # 22% - 24/25财年营收+21.5%/利润+36%,AI PC出货+228%,AI服务器+155%
    risk:
      mode: "SchemeC"
      beta: 1.05
      frag: 2.5

  # 2. 澜起科技 - 半导体内存接口（已分析）
  - name: "澜起科技"
    sector: "SEMI"
    expected_return: 0.40  # 40% - 2024利润+213%,DDR5全球份额36.8%第一,2025H1E+89-106%
    risk:
      mode: "SchemeC"
      beta: 1.15
      frag: 2.5

  # 3. 中金黄金 - 黄金矿企
  - name: "中金黄金"
    sector: "GOLD"
    expected_return: 0.15  # 15% - 2024矿产金约18吨(持平),主要受益金价上涨,纱岭金矿2025投产
    risk:
      mode: "SchemeC"
      beta: 0.95  # 黄金股,低波动
      frag: 2.0   # 脆弱度:金价波动,纱岭投产风险

  # 4. ASMPT - 半导体封装设备
  - name: "ASMPT"
    sector: "SEMI"
    expected_return: 0.28  # 28% - 2024营收-10%但先进封装+23%占比升至30%,TCB设备突破HBM市场
    risk:
      mode: "SchemeC"
      beta: 1.20  # 半导体设备,高周期
      frag: 3.0   # 脆弱度:SMT业务承压,行业周期

  # 5. 中天科技 - 光纤光缆+海缆
  - name: "中天科技"
    sector: "SEMI"  # 暂用半导体代理,通信设备
    expected_return: 0.12  # 12% - 2024营收+6.6%但利润-8.9%,光通信-10亿,海缆持平,行业低谷
    risk:
      mode: "SchemeC"
      beta: 1.10
      frag: 2.5   # 脆弱度:光纤光缆行业承压

  # 6. 中国巨石 - 玻纤龙头（已分析）
  - name: "中国巨石"
    sector: "NONFER"
    expected_return: 0.22  # 22% - 2024利润-19.7%但Q4筑底6.3亿,2025E利润+25%至30.5亿
    risk:
      mode: "SchemeC"
      beta: 1.20
      frag: 3.0

  # 7. 建滔积层板 - CCL覆铜板龙头
  - name: "建滔积层板"
    sector: "NONFER"  # 材料链,用有色金属风险代理
    expected_return: 0.30  # 30% - 2024年全球CCL市占率15%第一,受益PCB景气+AI服务器需求
    risk:
      mode: "SchemeC"
      beta: 1.05  # 材料周期,略高于行业
      frag: 2.0   # 脆弱度:需求波动

  # 8. 江西铜业 - 铜矿龙头
  - name: "江西铜业"
    sector: "NONFER"
    expected_return: 0.15  # 15% - 2024营收-0.18%,归母净利+7%,扣非+54%,铜资源889万吨
    risk:
      mode: "SchemeC"
      beta: 1.15  # 有色周期股
      frag: 2.5   # 脆弱度:铜价波动

  # 9. 紫金矿业 - 黄金+铜综合矿企
  - name: "紫金矿业"
    sector_mix:
      NONFER: 0.6  # 60%铜(107万吨,占营收主要)
      GOLD: 0.4    # 40%黄金(73吨)
    expected_return: 0.25  # 25% - 2024营收+3.5%,净利+52%至321亿,矿产铜+6%/金+8%,量价齐升
    risk:
      mode: "SchemeC"
      beta: 0.95  # 混合配置,低敏感
      frag: 1.5   # 脆弱度:商品价格波动,但资源丰富

  # 10. 雅克科技 - 半导体材料（已分析）
  - name: "雅克科技"
    sector: "SEMI"
    expected_return: 0.28  # 28% - 2024营收+44.84%/利润+50.41%,半导体材料+71.6%
    risk:
      mode: "SchemeC"
      beta: 1.20
      frag: 3.0

  # 11. 生益科技 - CCL覆铜板
  - name: "生益科技"
    sector: "NONFER"  # 材料链,用有色金属风险代理
    expected_return: 0.32  # 32% - 2024营收+22.92%/利润+50%,受益AI服务器+消费电子复苏
    risk:
      mode: "SchemeC"
      beta: 1.10  # 材料周期,中性
      frag: 2.5   # 脆弱度:下游需求波动

  # 12. 光迅科技 - 光模块+光器件
  - name: "光迅科技"
    sector: "SEMI"  # 暂用半导体代理,光通信
    expected_return: 0.38  # 38% - 2024营收+36.49%至82.72亿,2025Q1营收+72%/利润+95%,AI光模块放量
    risk:
      mode: "SchemeC"
      beta: 1.15  # 光通信高成长
      frag: 2.5   # 脆弱度:竞争激烈

  # 13. 特变电工 - 变压器+新能源
  - name: "特变电工"
    sector: "NONFER"  # 电力设备,用有色金属风险代理
    expected_return: 0.18  # 18% - 2024营收978亿/净利41亿,变压器+21%毛利率提升,但多晶硅-34%拖累
    risk:
      mode: "SchemeC"
      beta: 1.10  # 电力设备,中性
      frag: 2.0   # 脆弱度:多晶硅价格暴跌风险

  # 14. 川恒股份 - 磷化工+新能源材料
  - name: "川恒股份"
    sector: "NONFER"  # 化工,用有色金属风险代理
    expected_return: 0.28  # 28% - 2024营收+36.72%/利润+24.8%,磷化工+46.66%,磷矿产能扩张
    risk:
      mode: "SchemeC"
      beta: 1.15  # 化工周期
      frag: 2.5   # 脆弱度:磷矿价格,新能源材料不确定性

# ============================================================================
# 期望收益说明 - 基于2024年报及2025年预期的详细研究
# ============================================================================
#
# 【数据来源】基于2024年报实际业绩+2025年分析师预测+行业前景
#
# 极高增长(35-40%):
# - 澜起科技40%: 2024利润+213%,DDR5全球第一份额36.8%,2025H1E利润+89-106%
#   → 数据支撑:DDR5放量超预期,新产品PCIe/MRCD/MDB营收8倍,强劲增长持续
#
# - 光迅科技38%: 2024营收+36.49%,2025Q1营收+72%/利润+95%,AI光模块放量
#   → 数据支撑:全球光器件市占率5.8%第四,高速光模块产能爬坡,AI需求强劲
#
# 高增长(28-32%):
# - 生益科技32%: 2024营收+22.92%/利润+50%,全球CCL市占率12%第二
#   → 数据支撑:AI服务器+消费电子复苏,产品结构优化,毛利率提升
#
# - 建滔积层板30%: 全球CCL市占率15%第一,受益PCB景气+AI服务器
#   → 数据支撑:一体化布局成本优势,高端产品占比提升
#
# - 川恒股份28%: 2024营收+36.72%/利润+24.8%,磷化工+46.66%
#   → 数据支撑:磷矿产能扩张,20万吨湿法磷酸项目投产,新增资源量1616万吨
#
# - ASMPT 28%: 2024营收-10%但先进封装+23%占比升至30%,TCB突破HBM市场
#   → 数据支撑:先进封装5.05亿美元,目标35-40%TCB市占率,AI芯片需求
#
# - 雅克科技28%: 2024营收+44.84%/利润+50.41%,半导体材料+71.6%
#   → 数据支撑:国产替代加速,收购韩国SKC湿化学品业务
#
# 稳健增长(22-25%):
# - 紫金矿业25%: 2024营收+3.5%/净利+52%至321亿,铜+6%/金+8%量价齐升
#   → 数据支撑:矿产铜107万吨全球前四,矿产金73吨全球前六,资源储量丰富
#
# - 联想集团22%: 24/25财年营收+21.5%/利润+36%,AI PC出货+228%
#   → 数据支撑:Windows AI PC全球第一,AI服务器营收+155%
#
# - 中国巨石22%: 2024利润-19.7%但Q4筑底6.3亿,2025E利润+25%至30.5亿
#   → 数据支撑:玻纤价格持续修复,电子布复价,销量+21.9%
#
# 温和增长(15-18%):
# - 特变电工18%: 2024营收978亿,变压器+21%毛利率提升,但多晶硅-34%拖累
#   → 数据支撑:变压器产量4.20亿kVA行业前三,新能源业务承压
#
# - 江西铜业15%: 2024营收-0.18%,归母净利+7%,扣非+54%
#   → 数据支撑:铜资源889万吨,五家在产冶炼厂,国际化布局
#
# - 中金黄金15%: 2024矿产金约18吨持平,主要受益金价上涨
#   → 数据支撑:黄金储量891吨,纱岭金矿(200吨)2025投产
#
# 低增长/承压(12%):
# - 中天科技12%: 2024营收+6.6%但利润-8.9%,光通信-10亿,海缆持平
#   → 数据支撑:光纤光缆行业低谷,海缆在手订单134亿
#
# ============================================================================
# 行业代理说明
# ============================================================================
#
# SEMI (半导体):
# - 澜起科技、雅克科技、ASMPT、光迅科技、中天科技
#
# NONFER (有色金属):
# - 中国巨石、建滔积层板、江西铜业、生益科技、特变电工、川恒股份
#
# GOLD (黄金):
# - 中金黄金
#
# CONSUMER (消费):
# - 联想集团
#
# 混合行业:
# - 紫金矿业: 60%有色+40%黄金
#
# ============================================================================
